spring:
    cache:
        type: redis
        redis:
            time-to-live: 60000
    datasource:
        hikari:
            maximum-pool-size: 2
    main:
        allow-bean-definition-overriding: true
    redis:
        host: localhost
        port: 6379
